// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACKxh_TP1ekqB054o0ZvNhDTpBYtEIS7E',
    appId: '1:493718361762:web:324cc65694020dde6029fb',
    messagingSenderId: '493718361762',
    projectId: 'todo-app-5e07d',
    authDomain: 'todo-app-5e07d.firebaseapp.com',
    storageBucket: 'todo-app-5e07d.appspot.com',
    measurementId: 'G-SLLREWJN9G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2nM1r2On5dldKNO56L7kKm6GOV9OFUjc',
    appId: '1:493718361762:android:143d15deae73cd056029fb',
    messagingSenderId: '493718361762',
    projectId: 'todo-app-5e07d',
    storageBucket: 'todo-app-5e07d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEsCL1h18JjgNa1PuaeJQ2h0osPDLBRDw',
    appId: '1:493718361762:ios:e8ad76fc07db58d16029fb',
    messagingSenderId: '493718361762',
    projectId: 'todo-app-5e07d',
    storageBucket: 'todo-app-5e07d.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEsCL1h18JjgNa1PuaeJQ2h0osPDLBRDw',
    appId: '1:493718361762:ios:8202eade343e95096029fb',
    messagingSenderId: '493718361762',
    projectId: 'todo-app-5e07d',
    storageBucket: 'todo-app-5e07d.appspot.com',
    iosBundleId: 'com.example.todo.RunnerTests',
  );
}
